name: CI with coverage

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci-with-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: iwamot/actions/mise-validate@2ed40fde20f402e4f916d6727dbe029c236b57b1 # v0.1.3

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          use_oidc: true
