name: CI

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: iwamot/actions/mise-validate@f9102336df562777664ac310ce2dc9e4ca85941f # v0.1.0
