name: CI

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: iwamot/actions/mise-validate@cf0049402c5779ec08563b1e8067d25f8df7aef2 # v0.1.2
