name: CI

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: iwamot/actions/mise-validate@2ed40fde20f402e4f916d6727dbe029c236b57b1 # v0.1.3
