name: DCO

on:
  workflow_call:
  pull_request:
    branches: [ "main" ]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dco:
    name: dco
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: read  # to read PR commits for DCO sign-off check
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: KineticCafe/actions-dco@1da04282bbf757dab7d92a5c8535dbfb8113da5c # v3.1.0
