name: DCO

on:
  workflow_call:
  pull_request:
    branches: [ "main" ]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dco:
    name: dco
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: read  # to read PR commits for DCO sign-off check
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: KineticCafe/actions-dco@5f160e3ee086af8fc0fb567b8add0937d074123e # v3.2.0
