name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: write  # to create and publish the GitHub Release
    steps:
      - uses: iwamot/actions/release-draft@08456ce23ea73c42a50d71bd5a067d5ad68dc7e9 # v0.7.0
      - uses: iwamot/actions/release-publish@08456ce23ea73c42a50d71bd5a067d5ad68dc7e9 # v0.7.0