name: Validate

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: iwamot/actions/mise-validate@b7e018129d96b7170299c823014121079bce06d0 # v0.4.0
