name: Validate

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: iwamot/actions/mise-validate@792bb6f7b66b5d046aa285d39303a0aa7b10f822 # v0.5.0
