name: Validate with coverage

on:
  workflow_call:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-with-coverage:
    name: validate-with-coverage
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write  # for Codecov OIDC upload
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          egress-policy: audit

      - uses: iwamot/actions/mise-validate@09a90ef28919b6331a2930f6e61eeca11bc634de # v0.9.0

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          use_oidc: true
