name: Validate

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: iwamot/actions/mise-validate@dbe39b23ea600743e3fbb619d775ce08c61f753f # v2.0.1
